// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// defines a specific channel
type Channel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// message sent by a user to a specific channel
type Message struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Channel              *Channel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Message) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Message Ack
type MessageAck struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageAck) Reset()         { *m = MessageAck{} }
func (m *MessageAck) String() string { return proto.CompactTextString(m) }
func (*MessageAck) ProtoMessage()    {}
func (*MessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *MessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageAck.Unmarshal(m, b)
}
func (m *MessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageAck.Marshal(b, m, deterministic)
}
func (m *MessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageAck.Merge(m, src)
}
func (m *MessageAck) XXX_Size() int {
	return xxx_messageInfo_MessageAck.Size(m)
}
func (m *MessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_MessageAck proto.InternalMessageInfo

func (m *MessageAck) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Channel)(nil), "proto.Channel")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*MessageAck)(nil), "proto.MessageAck")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4f, 0x02, 0x31,
	0x10, 0xc5, 0xa9, 0x22, 0x1b, 0x67, 0x13, 0x13, 0xe7, 0x60, 0x36, 0x9c, 0xb4, 0x7a, 0xd8, 0xd3,
	0xae, 0xa0, 0x5f, 0x00, 0xf1, 0x82, 0x81, 0x98, 0xe0, 0xcd, 0x8b, 0x19, 0x6a, 0x43, 0x09, 0x6e,
	0xbb, 0xa1, 0xdd, 0xef, 0x6f, 0xb6, 0x7f, 0x42, 0xe0, 0x34, 0xf3, 0xe6, 0x75, 0xde, 0x2f, 0x53,
	0x00, 0xa1, 0xc8, 0x55, 0xed, 0xc1, 0x38, 0x83, 0x57, 0xbe, 0xf0, 0x09, 0x64, 0x73, 0x45, 0x5a,
	0xcb, 0x3f, 0x44, 0x18, 0x6a, 0x6a, 0x64, 0xc1, 0xee, 0x59, 0x79, 0xbd, 0xf6, 0x7d, 0x3f, 0xeb,
	0xac, 0x3c, 0x14, 0x17, 0x61, 0xd6, 0xf7, 0x9c, 0x20, 0x5b, 0x49, 0x6b, 0x69, 0x7b, 0xb4, 0xd9,
	0xd1, 0xc6, 0x12, 0x32, 0x11, 0x12, 0xfd, 0x56, 0x3e, 0xbd, 0x09, 0xc4, 0x2a, 0x72, 0xd6, 0xc9,
	0xc6, 0x02, 0xb2, 0x26, 0x04, 0x15, 0x97, 0x3e, 0x20, 0x49, 0xfe, 0x04, 0x10, 0x11, 0x33, 0xb1,
	0xc7, 0x3b, 0x18, 0x59, 0x47, 0xae, 0xb3, 0x91, 0x13, 0xd5, 0xd4, 0xc0, 0x70, 0xae, 0xc8, 0xe1,
	0x04, 0xf2, 0x0f, 0xb3, 0xd3, 0xe9, 0x8e, 0x33, 0xde, 0x38, 0xe9, 0x98, 0xc8, 0x07, 0xcf, 0x0c,
	0x5f, 0x21, 0xff, 0x92, 0xfa, 0x37, 0xdd, 0x71, 0xf6, 0x64, 0x7c, 0x7b, 0xaa, 0x67, 0x62, 0xcf,
	0x07, 0x25, 0x7b, 0x7b, 0xfc, 0x7e, 0xd8, 0xee, 0x9c, 0xea, 0x36, 0x95, 0x30, 0x4d, 0xbd, 0x58,
	0x2e, 0x17, 0xef, 0x9f, 0xab, 0xba, 0xff, 0xd4, 0x1f, 0x6a, 0xdb, 0xda, 0xef, 0x6c, 0x46, 0xbe,
	0xbc, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xcb, 0x18, 0xd9, 0x6d, 0x01, 0x00, 0x00,
}
